name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches: ['main', 'alpha', 'beta', 'rc']

jobs:
  build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Check out code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
            
        - name: Deploy to Coolify
          run: | 
            curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'  